services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dbnetwork

  mongo:
    image: mongo:latest
    env_file:
      - .env
    volumes: 
      - mongodata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - dbnetwork

  jupyter:
    # image, env, volumes, ports, etc ...
    image: contransimage
    env_file:
      - .env
    volumes: 
      - ./:/contrans
      - ./settings.txt:/root/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings
    ports:
      - "8890:8888"
      - "8080:8080"
    networks:
     - dbnetwork
 
volumes:
  postgresdata:
  mongodata:
 
networks:
  dbnetwork: